const ERROR_CODES = {
    INVALID_WALLET_ARG:0, 
    MISSING_WALLET_ARG:1,
    INVALID_BOT_ARG:2,
    MISSING_BOT_ARG:3,
    INVALID_COIN_ARG:4, 
    MISSING_COIN_ARG:5,
    INVALID_DEBUG_ARG:6,
    MISSING_DEBUG_ARG:7,
    INVALID_INTERVAL_ARG:8,
    MISSING_INTERVAL_ARG:9
}
module.exports = {ERROR_CODES}